name: CI

on:
  pull_request:
  push:
    branches: master

jobs:
  build:
    name: Type checking
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout pennyworth-ui
      uses: actions/checkout@v1

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Check for TypeScript errors
      run: |
        npm ci
        npm run type-check
      env:
        CI: true
