name: CI

on:
  pull_request:
  push:
    branches: master

jobs:
  build:
    name: Type checking
    runs-on: ubuntu-latest
    timeout-minutes: 1

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run install & lint
      run: |
        npm ci
        npm run lint
      env:
        CI: true
